import { GrammarExample } from '../types';

export const GRAMMAR_EXAMPLES: GrammarExample[] = [
  {
    id: 'ending-ab',
    title: "Strings Ending in 'ab'",
    description: 'Accepts any string over alphabet {a, b} that ends with the suffix "ab".',
    badge: 'Classic Example',
    grammar: `S → aS | bS | aA\nA → b`,
    testStrings: [
      { input: 'ab', shouldAccept: true },
      { input: 'aab', shouldAccept: true },
      { input: 'bab', shouldAccept: true },
      { input: 'bbab', shouldAccept: true },
      { input: 'aba', shouldAccept: false },
      { input: 'b', shouldAccept: false },
    ],
  },
  {
    id: 'even-zeros',
    title: 'Even Number of 0s',
    description: 'Generates all binary strings containing an even number of 0s, including ε.',
    badge: 'Parity Language',
    grammar: `S → 1S | 0A | ε\nA → 1A | 0S`,
    testStrings: [
      { input: '', shouldAccept: true },
      { input: '00', shouldAccept: true },
      { input: '1001', shouldAccept: true },
      { input: '010', shouldAccept: true },
      { input: '0', shouldAccept: false },
      { input: '000', shouldAccept: false },
    ],
  },
  {
    id: 'contains-01',
    title: "Contains Substring '01'",
    description: 'Language of binary strings containing at least one occurrence of "01".',
    badge: 'Substring Match',
    grammar: `S → 0S | 1S | 0A\nA → 1B\nB → 0B | 1B | ε`,
    testStrings: [
      { input: '01', shouldAccept: true },
      { input: '0010', shouldAccept: true },
      { input: '1101', shouldAccept: true },
      { input: '000', shouldAccept: false },
      { input: '111', shouldAccept: false },
    ],
  },
  {
    id: 'alternating-ab',
    title: 'Alternating a and b',
    description: 'Accepts strings of strictly alternating "a" and "b" (e.g. ab, aba, bab, baba, ε).',
    badge: 'Alternating',
    grammar: `S → aA | bB | ε\nA → bS | ε\nB → aS | ε`,
    testStrings: [
      { input: 'ab', shouldAccept: true },
      { input: 'aba', shouldAccept: true },
      { input: 'abab', shouldAccept: true },
      { input: 'baba', shouldAccept: true },
      { input: 'aab', shouldAccept: false },
      { input: 'bb', shouldAccept: false },
    ],
  },
  {
    id: 'starting-a-ending-b',
    title: "Starts with 'a' & Ends with 'b'",
    description: 'Accepts strings that begin with "a" and end with "b" with any symbols in between.',
    badge: 'Prefix/Suffix',
    grammar: `S → aA\nA → aA | bA | b`,
    testStrings: [
      { input: 'ab', shouldAccept: true },
      { input: 'aab', shouldAccept: true },
      { input: 'abb', shouldAccept: true },
      { input: 'aabab', shouldAccept: true },
      { input: 'ba', shouldAccept: false },
      { input: 'a', shouldAccept: false },
    ],
  },
  {
    id: 'identifier-token',
    title: 'Letter followed by Alphanumerics',
    description: 'A standard compiler token for identifiers starting with "x" followed by "x" or "0".',
    badge: 'Compiler Lexer',
    grammar: `S → xA | x\nA → xA | 0A | x | 0`,
    testStrings: [
      { input: 'x', shouldAccept: true },
      { input: 'xx', shouldAccept: true },
      { input: 'x0', shouldAccept: true },
      { input: 'xx0x', shouldAccept: true },
      { input: '0x', shouldAccept: false },
    ],
  },
];
